language: node_js

node_js:
- node

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: keboola/eslint-config-node
    branch: master
